# Generated by Django 2.1.2 on 2020-04-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200419_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_type', models.CharField(max_length=20)),
                ('second_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='first_type',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='second_type',
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commoditytype', to='app.CommodityType'),
        ),
    ]
