# Generated by Django 2.1.2 on 2020-04-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200421_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='order_nubmer',
            new_name='order_number',
        ),
    ]
