# Generated by Django 2.1.2 on 2020-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(max_length=255)),
                ('consequent', models.CharField(max_length=255)),
                ('conf', models.FloatField(default=0.0)),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
    ]
