# Generated by Django 2.1.2 on 2020-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_associationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='filename',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
