# Generated by Django 2.1.2 on 2020-05-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_commodity_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
