# Generated by Django 2.1.2 on 2020-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200505_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('min_support', models.FloatField(default=0.0)),
                ('min_conf', models.FloatField(default=0.0)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
    ]
