# Generated by Django 2.1.2 on 2020-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_associationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationrule',
            name='min_conf',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='associationrule',
            name='min_support',
            field=models.FloatField(default=25),
        ),
    ]
